-- Revert TIMESTAMP WITH TIME ZONE back to TIMESTAMP

ALTER TABLE platform_posts
  ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC',
  ALTER COLUMN edited_at TYPE TIMESTAMP USING edited_at AT TIME ZONE 'UTC',
  ALTER COLUMN crossposted_at TYPE TIMESTAMP USING crossposted_at AT TIME ZONE 'UTC';

ALTER TABLE platform_posts
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
