ALTER TABLE calls
  ADD COLUMN IF NOT EXISTS is_screen_sharing BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS screen_share_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS screen_share_ended_at TIMESTAMPTZ;
