ALTER TABLE bot_conversations
ADD COLUMN IF NOT EXISTS settings_user_name VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS settings_user_age VARCHAR(10) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS settings_user_gender VARCHAR(10) NOT NULL DEFAULT '';
