#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY="$ROOT/scripts/deploy-on.sh"
ROLLBACK="$ROOT/scripts/rollback.sh"
SAFE="$ROOT/scripts/safe-deploy.sh"
LIB="$ROOT/scripts/deploy-lib.sh"
HEALTH="$ROOT/scripts/deploy-health-contract.sh"
BOOTSTRAP="$ROOT/scripts/deploy-app.sh"
SETUP="$ROOT/scripts/deploy-setup.sh"
RUNBOOK="$ROOT/RUNBOOK.md"

bash -n "$DEPLOY"
bash -n "$ROLLBACK"
bash -n "$SAFE"
bash -n "$HEALTH"
bash -n "$BOOTSTRAP"
bash -n "$SETUP"

grep -Fq 'source "$SCRIPT_DIR/deploy-lib.sh"' "$DEPLOY"
grep -Fq 'source "$SCRIPT_DIR/deploy-lib.sh"' "$ROLLBACK"
grep -Fq 'run_local_preflight' "$DEPLOY"
grep -Fq 'run_remote_preflight' "$DEPLOY"
grep -Fq 'run_explicit_migrations' "$DEPLOY"
grep -Fq 'prompt_for_rollback' "$DEPLOY"

grep -Fq 'rollback_from_backup' "$ROLLBACK"
! grep -Fq 'git checkout' "$ROLLBACK"
! grep -Fq 'git stash' "$ROLLBACK"
! grep -Fq 'npm install' "$ROLLBACK"
! grep -Fq 'HEAD~1' "$ROLLBACK"

grep -Fq 'Use bash scripts/deploy-on.sh directly.' "$SAFE"
grep -Fq 'bash scripts/deploy-on.sh' "$RUNBOOK"
grep -Fq 'bash scripts/rollback.sh' "$RUNBOOK"
! grep -Fq 'Pre-warms Redis cache for `r/popular`' "$RUNBOOK"

test -f "$LIB"
bash -n "$LIB"

grep -Fq 'APP_ENV=production' "$BOOTSTRAP"
grep -Fq 'SERVER_HOST=127.0.0.1' "$BOOTSTRAP"
grep -Fq 'User=omninudge' "$BOOTSTRAP"
grep -Fq 'ProtectSystem=strict' "$BOOTSTRAP"
grep -Fq "script-src 'self'" "$BOOTSTRAP"
grep -Fq 'client_max_body_size 250M' "$BOOTSTRAP"
grep -Fq 'root:www-data dist' "$BOOTSTRAP"
grep -Fq 'access_log off' "$BOOTSTRAP"
grep -Fq 'location = /api/v1/ws' "$BOOTSTRAP"
grep -Fq 'proxy_pass http://127.0.0.1:8080' "$BOOTSTRAP"
! grep -Fq 'VITE_WS_URL' "$BOOTSTRAP"
! grep -Fq 'ALLOWED_ORIGINS=' "$BOOTSTRAP"
grep -Fq 'FRONTEND_URL=https://$DOMAIN,https://www.$DOMAIN' "$BOOTSTRAP"
! grep -Fq 'curl -fsSL https://deb.nodesource.com' "$SETUP"
grep -Fq 'sha256sum --check --strict' "$SETUP"
grep -Fq 'root -g www-data -m 0750 /var/www/omninudge' "$SETUP"
