-- Revert users.created_at and users.last_seen back to TIMESTAMP WITHOUT TIME ZONE

ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at AT TIME ZONE 'UTC',
  ALTER COLUMN last_seen TYPE TIMESTAMP WITHOUT TIME ZONE USING last_seen AT TIME ZONE 'UTC';

ALTER TABLE users
  ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
  ALTER COLUMN last_seen SET DEFAULT CURRENT_TIMESTAMP;
